//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApoForum.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public System.DateTime LastDate { get; set; }
    }
}
